name: CopyM8
options:
  bundleIdPrefix: com.vatsa
packages:
  HotKey:
    url: https://github.com/soffes/HotKey.git
    from: 0.1.3
targets:
  CopyM8:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources: [CopyM8]
    dependencies:
      - package: HotKey
    info:
      path: CopyM8/Info.plist
      properties:
        LSUIElement: true
        NSHighResolutionCapable: true
